import mongoose from "mongoose";

const softwareInstallationSchema = new mongoose.Schema(
  {
    softwareToken: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "SoftwareToken",
      required: true,
      index: true,
    },

    /*
     * Random ID generated by the Tauri installation.
     */
    systemId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
    },

    /*
     * Ed25519 public key.
     *
     * The corresponding private key NEVER
     * comes to the backend.
     */
    publicKey: {
      type: String,
      required: true,
      trim: true,
    },

    platform: {
      type: String,
      enum: [
        "windows",
        "macos",
        "linux",
        "android",
        "ios",
        "unknown",
      ],
      default: "unknown",
    },

    appVersion: {
      type: String,
      default: null,
    },

    status: {
      type: String,
      enum: ["active", "revoked"],
      default: "active",
      index: true,
    },

    activatedAt: {
      type: Date,
      default: Date.now,
    },

    lastSeenAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    timestamps: true,
  }
);

softwareInstallationSchema.index({
  softwareToken: 1,
  status: 1,
});

const SoftwareInstallation =
  mongoose.models.SoftwareInstallation ||
  mongoose.model(
    "SoftwareInstallation",
    softwareInstallationSchema
  );

export default SoftwareInstallation;